SELECT
	nus._id AS northstar_id,
	nus.country,
	nus.club_id,
	nus.birthdate,
	nus.drupal_id::VARCHAR,
	nus.email_subscription_status::int::bool,
	nus.created_at,
	nus.addr_zip,
	nus."language",
	nus."source",
	nus.updated_at,
	nus.CAMPAIGNS::jsonb,
	nus.audit::jsonb,
	nus.first_name,
	nus.email,
	nus.last_name,
	nus.addr_state,
	nus.addr_street_2,
	nus.addr_street_1,
	nus.addr_city,
	nus."role",
	nus.sms_status,
	nus.last_authenticated_at,
	nus.last_accessed_at,
	nus.mobile,
	nus.cio_backfilled,
	nus.addr_source,
	nus.source_detail,
	nus.last_messaged_at,
	nus.email_subscription_topics::jsonb,
	nus.sms_paused,
	nus.voting_plan_status,
	nus.voting_plan_time_of_day,
	nus.voting_plan_method_of_transport,
	nus.voting_plan_attending_with,
	nus.voter_registration_status,
	nus.facebook_id::varchar,
	nus.deleted_at::jsonb,
	nus.feature_flags::jsonb,
	nus.dbt_scd_id,
	nus.dbt_updated_at,
	nus.dbt_valid_from,
	nus.dbt_valid_to,
	nus.google_id,
	nus.causes::jsonb,
	nus.school_id,
	nus.referrer_user_id
FROM "quasar_prod_warehouse"."northstar_ft_userapi"."northstar_users_snapshot" nus
UNION ALL
SELECT
	nhu.id,
	nhu.country,
	NULL AS club_id,
	nhu.birthdate,
	nhu.drupal_id,
	nhu.email_subscription_status,
	nhu.created_at,
	nhu.addr_zip,
	nhu."language",
	nhu."source",
	nhu.updated_at,
	NULL AS CAMPAIGNS,
	NULL AS AUDIT,
	nhu.first_name,
	nhu.email,
	nhu.last_name,
	nhu.addr_state,
	nhu.addr_street2,
	nhu.addr_street1,
	nhu.addr_city,
	nhu."role",
	nhu.sms_status,
	nhu.last_authenticated_at,
	nhu.last_accessed_at,
	nhu.mobile,
	NULL AS cio_backfilled,
	nhu.addr_source,
	nhu.source_detail,
	nhu.last_messaged_at,
	NULL AS email_subscription_topics,
	NULL AS sms_paused,
	NULL AS voting_plan_status,
	NULL AS voting_plan_time_of_day,
	NULL AS voting_plan_method_of_transport,
	NULL AS voting_plan_attending_with,
	NULL AS voter_registration_status,
	nhu.facebook_id,
	NULL AS DELETED_AT,
	nhu.feature_flags::jsonb,
	NULL AS dbt_scd_id,
	NULL AS dbt_updated_at,
	NULL AS dbt_valid_from,
	NULL AS dbt_valid_to,
	NULL AS google_id,
	NULL AS causes,
	nhu.school_id,
	NULL AS referrer_user_id
FROM "quasar_prod_warehouse"."historical_analytics"."users" nhu